### PR TITLE
Updates CHANGELOG to match base.store's March Release Notes

### PR DESCRIPTION
**Pull request by danzanzini**
## What's the purpose of this pull request?

This PR updates the CHANGELOG so it matches it's [March Release Notes](https://faststore.dev/releases/2022/04/01/basestore). 
I've also added the identifier of the PR to each CHANGELOG entry so we don't need to rely on git blame to identify the PR responsible for the entry.

## How does it work?

Each entry that was merged before #392 was added to the 0.2.0 section. A new [Github release](https://github.com/vtex-sites/base.store/releases/tag/v0.2.0) was also added to reflect this state.

Each entry after this is still in the Unreleased section.

## How to test it?

Check if the CHANGELOG makes sense and doesn't have any wrong information.

## References
https://keepachangelog.com/en/1.0.0/

## Checklist

<em>You may erase this after checking them all ;)</em>

- [x] CHANGELOG entry added

### CODE REVIEW

**Review by Mariana-Caetano — APPROVED** [review]
Awesome @danzanzini! 🎉 Just one thing to add is that the PRs from February were mentioned in the [Full Changelog section of the Release Notes](https://github.com/vtex-sites/base.store/releases) (at the beginning of it) since the main focus was the March PRs. Either way LGTM.

**Comment by danzanzini** [comment]
@Mariana-Caetano Do you think it's worth creating a section below the 0.2.0 for entries from February?

**Comment by Mariana-Caetano** [comment]
> @Mariana-Caetano Do you think it's worth creating a section below the 0.2.0 for entries from February?

@danzanzini It sounds like a good idea, but do you mean also creating a 0.1.2 release to it?

**Comment by danzanzini** [comment]
A proper release is not necessary but I can create a tag to reflect the state of the code

**Pull request merged**
