### PR TITLE
refactor: Remove AspectRatio component

### PR DESCRIPTION
**Pull request by tlgimenes**
## What's the purpose of this pull request?
This PR removes the AspectRatio component in favor of using the builtin `aspectRatio` gatsby-plugin-image property

## How does it work?
AspectRatio component is only being used to add `aspect-ratio` to images. Gatsby has its own `aspectRatio` property. I think we can remove this component for now and gain some points on DOM's complexity level

## How to test it?
Nothing should have changed. Everything should work just fine

## Checklist
- [x] CHANGELOG entry added

### CODE REVIEW

**Comment by renatamottam** [comment]
Don't know if we should use this CSS property already, there're some browsers with no support with relevant use.
|Safari Desktop|Safari Mobile|Total users|
|-|-|-|
|Screen Shot 2022-02-14 at 15 02 25|Screen Shot 2022-02-14 at 15 03 53|Screen Shot 2022-02-14 at 15 04 08|

**Comment by tlgimenes** [comment]
I'm not sure. We already do not support these browsers because of our browserslist config

**Comment by tlgimenes** [comment]
Hey, I've just tested this PR on some unsupported browsers. Take a look how's the final layout on these browsers:
Iphone8:
iphone8

Safari 13:
safari13 1

I'm not sure, but it looks to me it's worth the perf improvements

**Comment by tlgimenes** [comment]
Ok, so I've managed to remove completely the `aspect-ratio` css property. Apparently Gatsby's `aspectRatio` does the job.

**Review by renatamottam — APPROVED** [review]
Looks good to me! 👏

**Review by hellofanny — APPROVED** [review]
LGTM 🚀

**Review by filipewl — APPROVED** [review]
LGTM! Just noticed some difference in the images in the `ProdcutTiles` component ("Just Arrived" section).

https://user-images.githubusercontent.com/381395/154569960-14ec01ad-8850-48aa-88d3-3f9ceab7728a.mp4

**Review by igorbrasileiro — APPROVED** [review]

**Pull request merged**
