### PR TITLE
feat(store-sdk): add cart

### PR DESCRIPTION
**Pull request by tlgimenes**
Adds cart to base.store. More info at: https://github.com/vtex/faststore/pull/913

### CODE REVIEW

**Comment by igorbrasileiro** [comment]
Can you create other PR just to add the cart provider? Now we can't measure the impact of this feature.

**Review by igorbrasileiro — CHANGES_REQUESTED** [review]
Can you decouple the cart feature from the other stuff, doing this we can measure the impact of the `cart provider`.

**Comment by tlgimenes** [comment]
> Can you decouple the cart feature from the other stuff, doing this we can measure the impact of the `cart provider`.

all this code only changes cart related code

**Comment by igorbrasileiro** [comment]
I realized that the product image inside the minicart is loading more than once.

**Comment by igorbrasileiro** [comment]
Maybe I've found a bug, I added a product and went to the checkout page, but there appear no items, this is intended to?

**Comment by tlgimenes** [comment]
> Maybe I've found a bug, I added a product and went to the checkout page, but there appear no items, this is intended to?

Yes, this is happening because the checkout is setting the cookie on the wrong domain. In production this would should work just fine

**Review by igorbrasileiro — COMMENTED** [review]
> > Maybe I've found a bug, I added a product and went to the checkout page, but there appear no items, this is intended to?
> 
> Yes, this is happening because the checkout is setting the cookie on the wrong domain. In production this would should work just fine

Ok, looks good.

**Pull request merged**
