### PR TITLE
Chore: fix CLS Lighthouse

### PR DESCRIPTION
**Pull request by eduardoformiga**
## What's the purpose of this pull request?
This PR attempts to fix the Cumulative Layout Shift CLS from the Lighthouse CI.

### CODE REVIEW

**Comment by filipewl** [comment]
Allow me to send an empty commit because the Gatsby Build task got stuck in the last commit.
CleanShot 2022-01-18 at 10 26 55

**Review by filipewl — APPROVED** [review]
Yay!

**Comment by hellofanny** [comment]
Uhull!

**Comment by eduardoformiga** [comment]
The problem was resolved on #250.

**Pull request closed without merging**
